### PR TITLE
megawifi: add tasking support

### PR DESCRIPTION
**Pull request by doragasu**
My first patch for the MegaWiFi support. This adds multitasking support (with a supervisor task and an user task and a basic locking mechanism).

As I am not familiar with SGDK sources, I might have done something weird. Please if you see something strange let me know.

I have made the compilation of the introduced code conditional as cleanly as I could. But adding too many `#if` is not very elegant, so if you have suggestions about doing this in a different manner, I can try.

### CODE REVIEW

**Comment by doragasu** [comment]
Added all the remaining sources, adapted to work with SGDK, without using newlib (I had to implement `memcmp`, `strchr` and workaround some problems due to some stuff from `stdint.h` and `stdbool.h` missing.

**Comment by doragasu** [comment]
And added an example. With this, I think all I wanted to add is there.

BTW, is there a problem with all this Codacity nonsense? It seems most (all?) the problems it finds are due to problems with headers (things like not finding definitions for `uint8_t`, etc.).

**Comment by Stephane-D** [comment]
Thanks the PR @doragasu !
To be honest there is more code than expected but i've to say it's a really nice framework you made there 👍 

I saw you even implemented a cooperative multitasking system through the v-int callback. It's really useful and something that i always wanted to add in SGDK. Do you think you can separate it from the MegaWifi framework itself so we can enable it separately ? I would even say that it could probably be always enable if the overhead isn't too heavy (we probably need to test is there is an active user task to not yield switch to user mode if not required).
Also i think it would be nice to have a sub folder like src/ext to separate base SGDK code from extension (or external) modules. So the MegaWifi related sources could be located in this src/ext sub folder.

And thanks for the LD script fix, i forgot to update the stack location after having changed the RAM location !

**Comment by Stephane-D** [comment]
Also glad you were able to get rid of the newlib requirement ! Can i borrow your memcpm and strchr functions so they will be directly included in SGDK mem / string unit ?

**Comment by doragasu** [comment]
Thanks for the review!

Sure, no problem, I can separate the multitasking from all the other MegaWiFi stuff. BTW the multitasking is preemptive (i.e. non cooperative). My previous approach (the one I implemented using `setjmp()/longjmp()` from newlib) used cooperative multitasking (using loop functions that had to return after doing the work), but most devs I talked to found that approach confusing, so I hope the preemptive multitasking is easier to use.

About the performance penalty of the multitasking when not being actively used, I could compute an estimate. I tried the Sonic example with it enabled and didn't see any difference in the CPU usage marker, but that's not a very objective test :-).

Also no problem moving my source files under `src/ext`. For the include files, do you want them to be in `inc/ext`? or maybe `inc/mw` (for MegaWifi) would be OK?

About my `memcmp()` and `strchr()`, they are not optimized, but sure, you can grab them if you want (I think `memcmp()` could be heavily optimized when buffers are aligned by subtracting long words instead of bytes) . If I can make a suggestion, these functions along with should be better in `string.h`, along with `memset()` and `memcpy()` to increase portability (they are defined in `string.h` in the standard C library). But if I can make even a bigger suggestion, for optimal portability I still think it would be better embracing newlib (yeah, yeah, I had to try :-)

**Comment by doragasu** [comment]
Added a multitasking example.

I have also found a bug in my multitasking implementation :-|. If you press the reset button in the console while the user task is running, you will get an access violation exception (presumably when the startup code tries to move 0x2700 to the status register). I think I should be able to fix it using a trap during startup to go back to privileged mode. But that will be tomorrow :-)

**Comment by doragasu** [comment]
Hum, about the bug, it is not happening in real hardware, so maybe it is a bug in Blastem.

**Comment by doragasu** [comment]
Last commit moves MegaWiFi sources to `src/ext/mw` and includes to `inc/ext/mw`. It also enables multitasking by default (but MegaWiFi continues disabled by default). Tested sonic, megawifi and multitask examples and everything builds and runs nice.

BTW the bug in my previous comments was in blastem, it was already fixed in nightly build.

**Comment by doragasu** [comment]
I did the cost calculation of the multitasking. If I did not screw the cycle counts, this is the result:

* The interrupt code adds 362 cycles:
image

* The `tsk_user_yield()` function adds 344 cycles (plus the `jsr` and maybe also clobberable registers save by caller):
image

Total is 706 CPU cycles (about a scanline and half). Not huge but not negligible either.

I will add the check in `vdp.c` to only call `tsk_user_yield()` if tasking is enabled. This should skip the call to `tsk_user_yield()` and lower the cycle count in VINT to just 18 (the `btst` and the `bne.s`). This way we should be able to keep `ENABLE_MULTITASK` always on with a negligible CPU penalty when not using it.

**Comment by Stephane-D** [comment]
Wow, thanks for all the modifications ! That sounds perfect :) I think it's indeed better to add a check as you did, indeed the tsk_user_yield() is still a bit taxing for the vblank handler that we want to keep as fast as possible.
About the memcpy / memcmp.. functions, i know they should be located in string.h but honestly for SGDK i don't necessary want to mimic too much how standard C organize stuffs, specially here with these memxxx functions which for me shouldn't really stand in the string.h unit. Also when you use SGDK, you're supposed to just include "genesis.h" so for portability i think it's better to have something like :
```
#if TARGET == MEGA_DRIVE
  #include <genesis.h>
#else
  #include <string.h>
  #include ..
#endif

```
Anyway you will need that switch in your code in different place as you will have specific code for MEGA_DRIVE target.
And that should be enough to make the _portable portions_ of code really portable as SGDK still try to use standard C function names (or alias for it) when it can.
Another point is that i really don't want SGDK to rely on any external library, i would even get rid of libgcc if I can but that would require quite a bit of work. There are already a switch to allow newlib compatibility but from what i read it doesn't work really well.

**Comment by doragasu** [comment]
Done, now yielding to user task during VBlank wait must be explicitly enabled by calling `VDP_setVBlankUserYield(TRUE)`.

I think with this all requested changes have been completed. @Stephane-D if you agree, now that CPU performance penalty when not using multitasking is negligible, I would like to remove the `ENABLE_MULTITASK` define to leave it always available and make the code cleaner (without all the ifdefs).

**Comment by Stephane-D** [comment]
> Done, now yielding to user task during VBlank wait must be explicitly enabled by calling `VDP_setVBlankUserYield(TRUE)`.
> 
> I think with this all requested changes have been completed. @Stephane-D if you agree, now that CPU performance penalty when not using multitasking is negligible, I would like to remove the `ENABLE_MULTITASK` define to leave it always available and make the code cleaner (without all the ifdefs).

I think we can indeed remove the ENABLE_MULTITASK define but don't worry I think I will merge as it is now and do not requires more changes from your side :) I will probably make some minor modifications to make it more SGDK conventions friendly if you don't mind (move the tsk_xx methods to a separate unit for instance and maybe rename them using TSK_xx as the others units).

**Review by Stephane-D — APPROVED** [review]
Good for merging 👍 
Thanks again @doragasu

**Review by Stephane-D — APPROVED** [review]

**Comment by doragasu** [comment]
Thanks for the merge!

I have finished rebasing the branch to master, but it seems I arrived late ^_^U.

I had a look to the new master and I think it will not be able to build sources in `src/ext` as is. I will open another PR with the changes.

**Comment by Stephane-D** [comment]
This time it's me which is late, i'm currently doing a bit of refactoring and i fixed the src/ext stuff.
I will push my changes as soon it will be complete (probably in 1 hour so i can test everything is ok)

**Comment by doragasu** [comment]
No problem. Thanks!!!

**Comment by Stephane-D** [comment]
Ok i just pushed the changes. I hope i didn't break anything but it looks like to be ok (tested with partial Megawifi support from BlastEm) =)

**Comment by doragasu** [comment]
Great, I'll give it a look. Thanks!

**Pull request merged**
