### PR TITLE
1.62 - Wine & Docker fix

### PR DESCRIPTION
**Pull request by LIZARDRIVE**
In a nutshell, I propose to:
- add "makefile_win.gen" to SGDK's root folder (works fine with 1.62)
- update Dockerfile so that it is based on this very same file rather than trying to get it from Github

Note that Dockerfile has been updated for AMD64 system, so other users may revert this line back to "FROM i386/debian:buster-slim"

### CODE REVIEW

**Comment by Stephane-D** [comment]
Is there anyway to directly use the makefile from SGDK github instead of having a separated one which need to be keep up to date ?

**Comment by LIZARDRIVE** [comment]
It seems to be feasible as we'd only need to modify RM/CP/SH and MKDIR related lines.
Seems that we could rely on a mecanism such as https://gist.github.com/sighingnow/deee806603ec9274fd47 in order to specify these variables based on OS..

**Comment by LIZARDRIVE** [comment]
I updated makefile.gen and it works for Linux.
Needs to be tested for Windows.

**Comment by paoloo** [comment]
it doesn't work, trying to build from OSX
```
 => ERROR [3/6] RUN export DEBIAN_FRONTEND='noninteractive' &&     apt-get update &&     apt-get install -y --no-install-recommends --no-install-suggests       make       openjdk-${JDK_VER}-jre-headless       wine &&     apt-get a  15.5s
 ...
#7 15.34 E: Unable to locate package openjdk--jre-headless
```

**Comment by paoloo** [comment]
it doesn't work on OSX
```
sample/sonic ( master ) $ docker run --rm -v `pwd`:/src sgdk
mkdir -p src/boot
mkdir -p out
cp /sgdk/src/boot/sega.s src/boot/sega.s
cp /sgdk/src/boot/rom_head.c src/boot/rom_head.c
/sgdk/bin/gcc -m68000 -Wall -Wextra -Wno-shift-negative-value -Wno-main -Wno-unused-parameter -fno-builtin -Iinc -Isrc -Ires -I/sgdk/inc -I/sgdk/res -B/sgdk/bin -c src/boot/rom_head.c -o out/rom_head.o
sh: 1: /sgdk/bin/gcc: not found
make: *** [/sgdk/makefile_wine.gen:167: out/rom_head.o] Error 127
```

**Comment by LIZARDRIVE** [comment]
> it doesn't work on OSX
> 
> ```
> sample/sonic ( master ) $ docker run --rm -v `pwd`:/src sgdk
> mkdir -p src/boot
> mkdir -p out
> cp /sgdk/src/boot/sega.s src/boot/sega.s
> cp /sgdk/src/boot/rom_head.c src/boot/rom_head.c
> /sgdk/bin/gcc -m68000 -Wall -Wextra -Wno-shift-negative-value -Wno-main -Wno-unused-parameter -fno-builtin -Iinc -Isrc -Ires -I/sgdk/inc -I/sgdk/res -B/sgdk/bin -c src/boot/rom_head.c -o out/rom_head.o
> sh: 1: /sgdk/bin/gcc: not found
> make: *** [/sgdk/makefile_wine.gen:167: out/rom_head.o] Error 127
> ```

Can you try compiling with makefile_wine instead of docker first?
Was original makefile working for you (official 1.62 version)?
If not, can you try compiling again after purging your project folder (see https://github.com/Stephane-D/SGDK/issues/199)?

**Comment by paoloo** [comment]
> 
> Can you try compiling with makefile_wine instead of docker first?

yes

> Was original makefile working for you (official 1.62 version)?

yes

> If not, can you try compiling again after purging your project folder (see #199)?

I purged it. It still happens
```
paolo@melchior ~/Workspace/SEGA/_/SGDK_LIZARDRIVE ( master) $ tail -2 Dockerfile
WORKDIR /src
ENTRYPOINT [ "make", "-f", "/sgdk/makefile_wine.gen" ]
paolo@melchior ~/Workspace/SEGA/_/SGDK_LIZARDRIVE ( master) $ docker build -t lizardrive/sgdk .
[+] Building 1.0s (11/11) FINISHED
 => [internal] load build definition from Dockerfile
 => => transferring dockerfile: 782B
 => [internal] load .dockerignore
 => => transferring context: 35B
 => [internal] load metadata for docker.io/amd64/ubuntu:focal
 => [1/6] FROM docker.io/amd64/ubuntu:focal@sha256:e3d7ff9efd8431d9ef39a144c45992df5502c995b9ba3c53ff70c5b52a848d9c
 => [internal] load build context
 => => transferring context: 13.78kB
 => CACHED [2/6] RUN mkdir -p /usr/share/man/man1
 => CACHED [3/6] RUN export DEBIAN_FRONTEND='noninteractive' &&     apt-get update &&     apt-get install -y --no-install-recommends --no-install-suggests       make       openjdk-14-jre-headless       wine &&     apt-get autoremov
 => CACHED [4/6] COPY . /sgdk
 => CACHED [5/6] WORKDIR /sgdk
 => CACHED [6/6] WORKDIR /src
 => exporting to image
 => => exporting layers
 => => writing image sha256:b60cae43b87e82139d9d5f781e915d54ac9033f4a62d1c3436441d6104d35ad9
 => => naming to docker.io/lizardrive/sgdk
paolo@melchior ~/Workspace/SEGA/_/SGDK_LIZARDRIVE ( master) $ cd sample/sonic/
aolo@melchior ~/Workspace/SEGA/_/SGDK_LIZARDRIVE/sample/sonic ( master) $ rm -rf out
paolo@melchior ~/Workspace/SEGA/_/SGDK_LIZARDRIVE/sample/sonic ( master !x) $ docker run --rm -v `pwd`:/src lizardrive/sgdk
mkdir -p src/boot
mkdir -p out
/sgdk/bin/gcc -m68000 -Wall -Wextra -Wno-shift-negative-value -Wno-main -Wno-unused-parameter -fno-builtin -Iinc -Isrc -Ires -I/sgdk/inc -I/sgdk/res -B/sgdk/bin -c src/boot/rom_head.c -o out/rom_head.o
sh: 1: /sgdk/bin/gcc: not found
make: *** [/sgdk/makefile_wine.gen:167: out/rom_head.o] Error 127
```

**Comment by LIZARDRIVE** [comment]
OK, so you are saying that revise makefile_wine.gen from this PR is working for you, right?

If not, can you post results doing the following commands
- make GDK=/home/paolo/sgdk162 -f /home/paolo/sgdk162/makefile.gen  (use original makefile coming with sgdk162)
- make GDK=/home/paolo/sgdk162 -f /home/paolo/sgdk162/makefile_win.gen  (use file from this PR)
- make GDK=/home/paolo/sgdk162 -f /home/paolo/sgdk162/makefile.gen  (use file from this PR)
from sample/sonic ?

If revised makefile_wine from this PR works, then please consider editing "FROM" line of docker file to match your system processor and OS.

**Comment by paoloo** [comment]
I do not have (a pure) gcc, wine or any other thing like that on my OSX fresh install(clang "emulates" gcc). All my build tools are running as docker images. Also, a `docker build` should not take in consideration what is running on the host computer, only what should run inside the containers itself. If there are extra things to do, add them to your Dockerfile, commit and I will test it

**Comment by mattsputnikdigital** [comment]
@LIZARDRIVE Im having the same issue, noticed an error in the PR before even getting docker build to work

openjdk-${JDK_VER}-jre-headless

needs to be changed to

openjdk-${JRE_VER}-jre-headless

**Comment by mattsputnikdigital** [comment]
Screenshot 2021-04-14 at 00 27 55

I created an Ubuntu install on VMWare, installed docker engine and downloaded SGDK, it gives the same error as on an OSX docker container.

**Comment by LIZARDRIVE** [comment]
Hello,
do you mean that changing the line on your first message solved the issue for you?

If not, can you please be so kind to answers questions listed here: https://github.com/Stephane-D/SGDK/pull/201#issuecomment-805091972 ? 

Thanks.

**Comment by mattsputnikdigital** [comment]
@LIZARDRIVE no it didn't solve the issue, just that line caused an error as well.

Currently getting the gcc: not found error as with @paoloo, on both OSX and Linux. I will try to answer the above questions, ive actually just got hello world building for the first time on a Windows VM, so im new to this so it will take a bit to time / I might not be much help.

**Comment by mattsputnikdigital** [comment]
@LIZARDRIVE sorry for the late reply

Running `make GDK=/Users/Matt/Sega/SGDK/ -f /Users/Matt/Sega/SGDK/makefile_wine.gen` gives the following error

`sh: /Users/Matt/Sega/SGDK//bin/gcc: No such file or directory`

So that looks to be the culprit, the double forward slash

**Comment by mattsputnikdigital** [comment]
@LIZARDRIVE running `make GDK=/Users/Matt/Sega/SGDK -f /Users/Matt/Sega/SGDK/makefile_wine.gen` gives the error

```
/Users/Matt/Sega/SGDK/bin/gcc -m68000 -Wall -Wextra -Wno-shift-negative-value -Wno-main -Wno-unused-parameter -fno-builtin -Iinc -Isrc -Ires -I/Users/Matt/Sega/SGDK/inc -I/Users/Matt/Sega/SGDK/res -B/Users/Matt/Sega/SGDK/bin -c src/boot/rom_head.c -o out/rom_head.o
sh: /Users/Matt/Sega/SGDK/bin/gcc: No such file or directory
```

**Comment by LIZARDRIVE** [comment]
Was makefile in SGDK 1.60 working for you?
If so, then docker aside you have an issue with the new way of working of makefile since 1.62.

**Comment by Elazul** [comment]
Hi! I've managed to compile the sample projects with no issue using this fix PR https://github.com/LIZARDRIVE/SGDK_LIZARDRIVE/pull/2 . Please let me know if it works for you folks :) !

**Comment by Elazul** [comment]
@LIZARDRIVE did you have some time to try out the fix and review my PR https://github.com/LIZARDRIVE/SGDK_LIZARDRIVE/pull/2 ?

**Comment by LIZARDRIVE** [comment]
Hello @Elazul ! Sorry I was not very active for a while.
Your solution works perfectly and I merged it.
Big thanks to you!

**Comment by pladaria** [comment]
why is the specific `makefile_wine.gen` file needed?

I tried your branch changing the docker entrypoint to:
```
ENTRYPOINT [ "make", "-f", "/sgdk/makefile_wine.gen" ]
```
and it builds the sonic sample without problems

**Comment by Elazul** [comment]
> why is the specific `makefile_wine.gen` file needed?
> 
> I tried your branch changing the docker entrypoint to:
> 
> ```
> ENTRYPOINT [ "make", "-f", "/sgdk/makefile.gen" ]
> ```
> 
> and it builds the sonic sample without problems.
> 
> These are the differences between the two files:
> `git diff --no-index makefile.gen makefile_wine.gen`
> 
> ```diff
> diff --git a/makefile.gen b/makefile_wine.gen
> index b026d8b..851bdb5 100644
> --- a/makefile.gen
> +++ b/makefile_wine.gen
> @@ -1,3 +1,8 @@
> +RM= rm^M
> +CP= cp^M
> +MKDIR= mkdir^M
> +SHELL= sh^M
> +^M
>  MAKEFILE_DIR:= $(dir $(lastword $(MAKEFILE_LIST)))
>  MAKEFILE_DIR:= $(subst \,/,$(MAKEFILE_DIR))
>  
> @@ -16,21 +21,6 @@ SRC:= src
>  RES:= res
>  INCLUDE:= inc
>  
> -
> -OSFLAG                                 :=
> -ifeq ($(OS),Windows_NT)
> -       SHELL:= $(BIN)/sh
> -       RM:= $(BIN)/rm
> -       CP:= $(BIN)/cp
> -       MKDIR:= $(BIN)/mkdir
> -else
> -       RM= rm
> -       CP= cp
> -       MKDIR= mkdir
> -       SHELL= sh
> -endif
> -
> -
>  CC:= $(BIN)/gcc
>  LD:= $(BIN)/ld
>  NM:= $(BIN)/nm
> ```
> 
> So I'd say the `makefile_wine.gen` could be removed

I think @LIZARDRIVE removed the specific case on Windows OS because there is no point about running a Docker image based on Windows. Any light Linux distrib would fit better for this use case in my opinion! Still the file could be renamed `makefile_docker.gen`, that would be more meaningful.

**Comment by pladaria** [comment]
> I think @LIZARDRIVE removed the specific case on Windows OS because there is no point about running a Docker image based on Windows. Any light Linux distrib would fit better for this use case in my opinion! Still the file could be renamed `makefile_docker.gen`, that would be more meaningful.

I think it would be better to have a single makefile (less stuff to maintain). 

Perhaps those cli tools that are not called using wine could be called inside a bash script:

insted of:
```bash
#!/bin/bash
WINEDEBUG=-all WINEPREFIX=/sgdk/bin/.wineconf wine /sgdk/bin/mkdir.exe "$@"
```

simply:
```bash
#!/bin/bash
mkdir "$@"
```

This way the makefile.gen should work for windows and docker without changes or OS specific conditions

**Comment by Stephane-D** [comment]
> I think it would be better to have a single makefile (less stuff to maintain).
> 
>..
>
> This way the `makefile.gen` should work for windows and docker without changes or OS specific conditions

I didn't followed the whole thread but indeed, that comment make sense :) having something simple to maintain and which can stay compatible with the original _makefile.gen_ would be really nice !

**Comment by LIZARDRIVE** [comment]
I got rid of makefile_wine.gen as I already updated makefile.gen to handle OS detection indeed. 
Thanks guys for your support!

**Review by Stephane-D — APPROVED** [review]
Seems to be all good now, thanks everyone who participated to the MR !

**Comment by mattsputnikdigital** [comment]
I havent had a chance to test this yet, but thanks for working on a solution. Will test on OSX as soon as I get a moment!

Thanks!

**Comment by Stephane-D** [comment]
Don't hesitate to report your feedback / troubleshoot here. I didn't tested it myself !

**Comment by pladaria** [comment]
Verified on MacOS 10.15.7

**Comment by Stephane-D** [comment]
Well afaik the MR is not ok, native SGDK doesn't compile anymore, because of the 
"-ifeq ($(OS),Windows_NT)" condition.
When using classic make from windows, this variable isn't defined and those, end using wrong alias.

**Comment by LIZARDRIVE** [comment]
Woops! :-D

**Comment by jespicas** [comment]
Hi!
I tried to build a Sonic Example and have problems not found xgmtool

Resource: XGM sonic_music "music/sonic1.vgm"
--> executing plugin XGM...Executing /sgdk/bin/xgmtool /src/res/music/sonic1.vgm /src/res/music/sonic1.bin -s   
SystemUtil.exec([Ljava.lang.String;@1da6444) error :
Cannot run program "/sgdk/bin/xgmtool" (in directory "."): error=2, No such file or directory
Exception in thread "main" java.lang.NullPointerException
	at sgdk.rescomp.tool.Util.xgmtool(Util.java:607)
	at sgdk.rescomp.processor.XgmProcessor.execute(XgmProcessor.java:61)
	at sgdk.rescomp.Compiler.execute(Compiler.java:678)
	at sgdk.rescomp.Compiler.compile(Compiler.java:134)
	at sgdk.rescomp.Launcher.main(Launcher.java:65)
make: *** [/sgdk/makefile.gen:212: res/sound.rs] Error 1
rm res/gfx.rs

**Comment by pladaria** [comment]
> Hi!
> I tried to build a Sonic Example and have problems not found xgmtool

See this comment
https://github.com/Stephane-D/SGDK/commit/d02ca0e39d9925c0f2733431451e741d25f0d020#comments

If you restore the `bin/xgmtool` exe wrapper it should work.
@Stephane-D was that file removed on purpose or was an error?

**Comment by Stephane-D** [comment]
Oups my fault this time, indeed it needs to be restored. I removed it as it prevents rescomp working on native Windows as it will try to execute the wrapper instead of the good xgmtool.exe
I though the xgmtool wrapper was not needed as only used by rescomp.
I think it would be better if we could have a separate folder for docker so we would have the wrappers into sgdk/docker/bin or something like that. Avoiding messing up with native SGDK binaries.

**Comment by pladaria** [comment]
> I think it would be better if we could have a separate folder for docker so we would have the wrappers into sgdk/docker/bin or something like that

Perhaps a better option would be to simply generate the wrappers at `docker build`. I can prepare a PR for that

**Comment by Stephane-D** [comment]
That sounds like a good idea indeed 👍

**Pull request merged**
