### PR TITLE
libmd compilation in Visual Studio

### PR DESCRIPTION
**Pull request by lab313ru**
Added solution for compiling libmd.a without using makefiles.

### CODE REVIEW

**Comment by lab313ru** [comment]
So, why this pullrequest is still pullrequest? Any mistakes, disagrees with my code?

**Comment by Stephane-D** [comment]
I need a bit of time to inspect and test it, it looks like to add a lot of specific VS files right ? is it possible to isolate (at best) them in a VS folder ?

**Comment by lab313ru** [comment]
They are all located in `vstudio` folder.

**Comment by Stephane-D** [comment]
Ok, i will have a look on it soon so :)

**Comment by lab313ru** [comment]
Just updated to use SGDK v1.3.0 flags.

**Pull request merged**
