### PR TITLE
Build strclr and strreplacechar when enabling newlib

### PR DESCRIPTION
**Pull request by doragasu**
These functions are not part of the C standard library (and not included in newlib) and thus must be built when newlib is enabled. Otherwise the library fails to build because of these symbols missing.

I have just moved them out of the `#if (ENABLE_NEWLIB == 0)` blocks.

### CODE REVIEW

**Comment by doragasu** [comment]
Pushed another commit that fixes implicit declarations of functions removed when defining ENABLE_NEWLIB 1. This happens for example when:
* In your program using newlib, you `#include <string.h> and use for example `strcpy()`
* The `string.h` file gets included, and since declaration for `strcpy()` has been removed, you get an implicit declaration warning.

The fix uses `#include_next` GCC extension. It also adds an `#include <string.h> to the `src/pal.c` file, since in the standard C library, `memcpy()` is defined in `string.h` and thus was not getting included when enabling newlib.

**Comment by doragasu** [comment]
`#include_next` is a GCC extension (not standard C unfortunately). In the undesirable case when several include files have the same name, when your program makes the `#include <file.h>`, only one of them gets included (depending on the compiler installation, the `-I` switches, etc. In this case, what the `#include_next` does, is including the next file in the chain with the same name.

So, in this case, for example, my application does `#include <string.h>`, and the `string.h` file in SGDK gets included. But I wanted stuff from the newlib `string.h` file, so the `#include_next` directive will include for me the `string.h` file from newlib.

I can make the change to the include guards to keep the `_SGDK_STRING_H_`. It will make the `#if` directives a bit more tangled, but should not be a problem.

Thanks for review!

**Comment by doragasu** [comment]
Done! (forced pushed).
It might look a bit dirty because of the `#undef _STRING_H_`, but if you want to preserve the `_STRING_H_` guard name, this is the best approach I could think of.

**Comment by doragasu** [comment]
Thanks!

I usually write "Jesús Alonso (doragasu)"

If you prefer avoiding non-english characters, you can use "Jesus Alonso (doragasu)"

**Comment by Stephane-D** [comment]
Ok perfect, i will use the non-english characters version if you don't mind :)

**Pull request merged**
