### PR TITLE
Fix text output for ASCII codes more then 127

### PR DESCRIPTION
**Pull request by starling13**

### CODE REVIEW

**Comment by Stephane-D** [comment]
How does this actually fix ASCII code > 127 (as there are not supported anyway in the FONT table) ??

**Comment by matteusbeus** [comment]
I was about to say the myself!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Stephane-D** [comment]
I guess you can use it loading your own font then ;)

**Comment by starling13** [comment]
Yes, I'v modified the font to match KOI8-R cyrillyc encoding, adding extra symbols.
If one increase the font table size and use all 255 char codes, this change is necessary.

**Comment by Stephane-D** [comment]
Ok, that makes sense. I merged the commit :)
Thanks for your contribution 👍

**Comment by matteusbeus** [comment]
Won't this take more VRAM?
________________________________

**Comment by matteusbeus** [comment]
Must be just under 4kb with the additional characters right?

________________________________

**Pull request merged**
