### PR TITLE
Updated to use GCC 13.2.0

### PR DESCRIPTION
**Pull request by iratahack**
Updated the compiler and debugger to newer versions.

* GCC 13.2.0
* GDB 13.2

The benchmark app reports a better total score so optimizations are slightly improved with this version.
IH.

### CODE REVIEW

**Review by iratahack — COMMENTED** [review]
Changes tested on Windows standalone and work fine.

**Comment by joeyparrish** [comment]
The Windows binaries are no longer the only way to run SGDK.  Could you also update the Docker files to build GCC 13?  Otherwise, your change will only affect Windows users.

**Comment by iratahack** [comment]
@joeyparrish , the current docker build already includes gcc 13. This PR is to bring the Windows environment up to the same spec while maintaining backward compatibility.

**Comment by joeyparrish** [comment]
Cool, thanks.  Sorry I didn't notice.

**Pull request merged**
