### PR TITLE
New SGDK logo

### PR DESCRIPTION
**Pull request by LIZARDRIVE**
New SGDK logo made by twitter.com/iamgunpog

### CODE REVIEW

**Comment by matthewbennion** [comment]
Personally I prefer the sketch of Sonic! But if Stef likes this logo...

**Comment by matteusbeus** [comment]
Personally I prefer the sketch of Sonic! But if Stef likes this logo...

**Comment by Stephane-D** [comment]
Hehe, i really like this one, but i will keep the sonic as legacy one ;)

**Comment by CristianoSword** [comment]
the logo looks really good!

**Pull request merged**
