### PR TITLE
Mark the boot asm as KEEP, for gc-sections

### PR DESCRIPTION
**Pull request by clbr**
gc-sections is one of the ways GCC can create smaller binaries. This would also be needed for LTO, but I didn't try LTO yet.

### CODE REVIEW

**Comment by Stephane-D** [comment]
Honestly i don't see what it can change when it comes to sega megadrive development ?
I mean the boot section is always located at 0x000000 else it just doesn't work. I don't see how it can reduce binary size here.
Are your changes compatible with older GCC as version 3.4.X ?

**Comment by clbr** [comment]
On Tue, 17 Nov 2015 12:42:16 -0800
Stephane Dallongeville <notifications@github.com> wrote:

> Honestly i don't see what it can change when it comes to sega megadrive development ?
> I mean the boot section is always located at 0x000000 else it just doesn't work. I don't see how it can reduce binary size here.
> Are your changes compatible with older GCC as version 3.4.X ?

If you enable the appropriate options, your program will be smaller,
because GCC/ld can remove unused sections better. Without this patch,
the result is a broken ROM, as the boot section gets removed too.

Many programs get up to 20% smaller with gc-sections, such as the Linux
kernel and busybox.

The patch requires at least binutils 2.18 which was released in 2008.
It does nothing if the GCC and linker options aren't enabled, and so
early GCC will be fine, as long as binutils is new enough.

**Comment by Stephane-D** [comment]
Ok, i will test that patch on my windows setup with GCC 3.4.6 (which is the default setup in SGDK) and if it work i will apply the merge operation. Thanks for your contribution :)

**Comment by clbr** [comment]
On Wed, 18 Nov 2015 01:31:39 -0800
Stephane Dallongeville <notifications@github.com> wrote:

> Ok, i will test that patch on my windows setup with GCC 3.4.6 (which is the default setup in SGDK) and if it work i will apply the merge operation. Thanks for your contribution :)

Can I ask why is the Windows default so old? I use it on Linux via
gendev, and it's on GCC 4.8.

**Comment by Stephane-D** [comment]
Because older GCC generate better code for old CPU (as 68k family). Newer GCC code generation is very convoluted and that really impacts final performance (i observed up to 40% slower code) and code size is bigger as well.

**Comment by clbr** [comment]
On Wed, 18 Nov 2015 04:47:36 -0800
Stephane Dallongeville <notifications@github.com> wrote:

> Because older GCC generate better code for old CPU (as 68k family). Newer GCC code generation is very convoluted and that really impacts final performance (i observed up to 40% slower code) and code size is bigger as well.

Oh, ok. This isn't really relevant to this ticket, but m68k is an
active port with more users than just Genesis - it would be helpful to
test new GCC releases and report such issues when they appear, if your
performance regression was still there in 5.2.0, for one.

**Comment by Stephane-D** [comment]
Yeah of course but still m68k target is rarely used today and GCC compiler tend to optimize their code generation for newer CPU with very complex architecture resulting in very poor code for older CPU generations. From my (few) tests GCC 5 was even worst than 4.X here :-/
That is a shame as the GCC version i'm using (3.4.6) has some bugs (inline and register keyword does not work)... The best version for m68k is probably GCC 2.8.X as far i remember but too much outdated...

**Comment by Stephane-D** [comment]
I tried to report that issue (bad code generation for m68k target) but honestly they just don't care.

**Comment by clbr** [comment]
I think I saw your bug, it went without attention for a couple years, but it's fixed in current GCC.

Also, sorry about the wavtoraw commits, I'll create a separate pull for those.

**Comment by Stephane-D** [comment]
Do you mean that new GCC does now generate good code for m68k ? Honestly i could bet that is not the case...

**Comment by clbr** [comment]
If it was this bug, it's fixed, and the fix is present in 5.2:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=52773

I can't say whether the codegen is good.

**Comment by Stephane-D** [comment]
Not exactly the same : https://gcc.gnu.org/bugzilla/show_bug.cgi?id=52897
I don't know how much 52773 is the same or not.
But you can test by yourself, you have here material and comparison of output :
https://gcc.gnu.org/bugzilla/attachment.cgi?id=27110&action=edit
So if you're using the last GCC version you can see how much code generation is improved (or not)

**Comment by clbr** [comment]
On Wed, 18 Nov 2015 07:08:23 -0800
Stephane Dallongeville <notifications@github.com> wrote:

> Not exactly the same : https://gcc.gnu.org/bugzilla/show_bug.cgi?id=52897
> I don't know how much 52773 is the same or not.
> But you can test by yourself, you have here material and comparison of output :
> https://gcc.gnu.org/bugzilla/attachment.cgi?id=27110&action=edit
> So if you're using the last GCC version you can see how much code generation is improved (or not)

I could, except I don't speak enough ASM to tell what is better or not,
sadly.

**Comment by Stephane-D** [comment]
Can you eventually send me the ASM output with your GCC on the bmp.c file provided ?
But just checking here, you can see the ASM listing of GCC 4.X is about 3 times longer than the GCC 3.X one, it's already a good indication there is definitely something wrong with the code generation with later compiler. And when it comes to old CPU as 68000, having a good compiler is important.

**Comment by clbr** [comment]
Here you go:
http://pastebin.ca/3259906

GCC 5.2 at -O3. Going by size alone, it's even better than GCC 3. I did hit a bug in building 5.2 for m68k:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68419

**Comment by Stephane-D** [comment]
Thanks ! Unfortunately it looks like the optimization bug is not fixed even if some parts look better. If that is possible i would like to see the result with "-O2 -fno-gcse" switchs :)
You said you experienced a bug with GCC 5.2 compilation for m68k, how did you sorted it ?

**Comment by clbr** [comment]
On Wed, 18 Nov 2015 12:31:45 -0800
Stephane Dallongeville <notifications@github.com> wrote:

> Thanks ! Unfortunately it looks like the optimization bug is not fixed even if some parts look better. If that is possible i would like to see the result with "-O2 -fno-gcse" switchs :)
> You said you experienced a bug with GCC 5.2 compilation for m68k, how did you sorted it ?

Sorry, I don't have the build anymore. I worked around the ICE by using
the first pass xgcc, which was built by my host compiler - the segfault
was when gcc tried to build itself again to test itself. For production
use, better wait until the bug is fixed.

**Comment by Stephane-D** [comment]
Ok, well at least i merged the pull request :)
It would be nice if they could fix the simple memory to memory transfer optimization operation as this is a huge advantage the 68k offers.

**Pull request merged**
