### PR TITLE
Rescomp : timer customizable

### PR DESCRIPTION
**Pull request by tulf95**
You can choose between 3 timers syntax , exemple : 

SPRITE .... FAST 8             --> 8 applied to all frame and all animations

SPRITE .... FAST 8|7|6       --> 8 applied to first anim line, 7 to second anim line, 6 to third anim line

SPRITE .... FAST 8|7,6,5|6  --> 8 applied to first anim line, in the second anim line : 7 to the first frame, 6 to the 2nd, 5, to the 3rd, 6 to third anim line

### CODE REVIEW

**Comment by TheRoboZ** [comment]
This is a great idea but can it also not break compatibility if we just leave the current syntax format?

**Comment by tulf95** [comment]
> This is a great idea but can it also not break compatibility if we just leave the current syntax format?

Hi,
It works just fine with current syntax.

**Comment by TheRoboZ** [comment]
Oh, sorry I misread the first example. Great. I hope this gets approved.

**Comment by Stephane-D** [comment]
Thanks ! I just pushed a commit to bring this feature, just using a different syntax for the multiples value (more in classic array format)

**Comment by D0NM** [comment]
Good day!

Behavior of SpriteFrameChangeCallback function has changed.
Before I could alter the duration of the frame right in the callback like you suggested:
**sprite->timer = NEW_CUSTOM_DURATION;**

All our sprites were defined with TIMER == 0 (by default)
The callback is called once on the 1st frame.
This line doesnt' work like it used to.
**sprite->timer = NEW_CUSTOM_DURATION;**  

I suppose you override altered by me sprite->timer value.

My sprite engine wrapped is dead. Digging into your sources V__V

**Comment by Stephane-D** [comment]
> Good day!
> 
> Behavior of onFrameChange callback function has changed. Before I could alter the duration of the frame right in the callback like you suggested: **sprite->timer = NEW_CUSTOM_DURATION;**
> 
> All our sprites were defined with TIMER == 0 (by default) The callback is called once on the 1st frame. This line doesn't work like it used to. **sprite->timer = NEW_CUSTOM_DURATION;**
> 
> My sprite engine wrapped is dead. Digging into your sources V__V
> 
> I suppose it is because all AnimationFrame data has a proper timer value. (I used to check default timer value)

Sorry for that, indeed I screwed up the timer update in the callback ! Should be fixed with the last commit :)

**Pull request closed without merging**
