### PR TITLE
Lowercase org name when constructing docker tag names

### PR DESCRIPTION
**Pull request by joeyparrish**
This resolves errors like:

Error: buildx failed with: ERROR: invalid tag "ghcr.io/Stephane-D/sgdk-m68k-gcc:latest": repository name must be lowercase

For example, see https://github.com/Stephane-D/SGDK/actions/runs/8545289521/job/23413232803

This also fixes several additional workflow issues that occurred during debugging and development:

 - Build logs from crosstool-ng were overwhelming (180k+ useless lines of a progress bar), now disabled with CT_LOG_PROGRESS_BAR=n
 - Bootstrapping for first GCC image on main repo or fork was broken, now fixed to ensure workflow's GCC image used in later SGDK image.

### CODE REVIEW

**Comment by joeyparrish** [comment]
JFYI, builds are failing in CI until #322 is merged.

**Comment by joeyparrish** [comment]
Rebased on top of fix in #322

**Review by Stephane-D — APPROVED** [review]

**Comment by joeyparrish** [comment]
I deleted the GCC image from my own account and created a PR to myself to prove that the bootstrapping steps work.  The defaults set by Docker's official GitHub Action don't match the defaults you have locally when running the same build commands.  This took a while to figure out.

I also changed it to build using the org name of the repo the PR targets, so this workflow run will show you that it should work for you on push as well.  Any push or PR merge will publish a new official package to GHCR.

**Comment by joeyparrish** [comment]
All workflows passing.  Ready to merge when you are.  Thanks!

**Comment by joeyparrish** [comment]
@Stephane-D, I see you have approved, but not yet merged.  Can you please merge this?

I'm ready to start referring to official SGDK builds in my projects instead of my forked version of SGDK, but because of this case-sensitivity issue, official Docker builds aren't being published from your repo yet.

Thanks!

**Review by Stephane-D — APPROVED** [review]

**Review by Stephane-D — APPROVED** [review]

**Pull request merged**
